/// <summary>
/// Calculates the thrust force generated by the rocket engine.
/// </summary>

using System;
using AeroSim.Core.Mathematics;
using AeroSim.Core.Models;

namespace AeroSim.Simulation.Forces;

public sealed class ThrustForce : IForceModel
{

    // ---------------------------
    // Dependencies
    // ---------------------------

    private readonly RocketConfiguration _rocket;

    // ---------------------------
    // Construction
    // ---------------------------

    public ThrustForce(RocketConfiguration rocket)
    {
        _rocket = rocket ??
            throw new ArgumentNullException(nameof(rocket));
    }


    // ---------------------------
    // Force calculation
    // ---------------------------

    public Vector2D CalculateForce(VehicleState state)
    {
        ArgumentNullException.ThrowIfNull(state);
        
        bool engineIsBurning = state.TimeSeconds < _rocket.Engine.BurnDurationSeconds && state.FuelMassKg > 0;

        if (!engineIsBurning)
        {
            return Vector2D.Zero;
        }

        double angleRadians = _rocket.Engine.ThrustAngleDegrees * Math.PI / 180.0;

        Vector2D direction = new(Math.Cos(angleRadians),Math.Sin(angleRadians));

        return direction * _rocket.Engine.ThrustNewtons;
    }
}